-- =========================================================================
-- RobooTeam - estrutura do banco de dados (Supabase / PostgreSQL)
--
-- Rode este arquivo inteiro no SQL Editor do Supabase. Ele pode ser
-- executado de novo sem apagar dados (usa "if not exists").
--
-- Tabelas:
--   usuarios           alunos e a professora (cadastro e login)
--   progresso_trilha   etapas da trilha concluídas por cada aluno
--   progresso_jogo     fases do jogo de programação concluídas
--   trilha_atividades  trilha personalizada criada pela professora
--   arenas             partidas da Arena RobooTeam
--   arena_equipes      equipes de cada arena
--   arena_jogadores    alunos jogando em cada arena
--
-- O servidor Flask acessa o banco pela string de conexão (DATABASE_URL).
-- O RLS fica ativo e sem políticas, então as chaves públicas da API do
-- Supabase não conseguem ler nem alterar nada (nem os hashes de senha).
-- =========================================================================

-- -------------------------------------------------------------- usuários
create table if not exists public.usuarios (
    id               bigint generated by default as identity primary key,
    nome             text not null check (char_length(nome) between 3 and 80),
    email            text not null unique
                     check (email = lower(email) and char_length(email) <= 254),
    senha_hash       text not null,
    perfil           text not null default 'ALUNO'
                     check (perfil in ('ALUNO', 'PROFESSOR')),
    disciplina       text,
    -- sala da professora
    turma_nome       text,
    codigo_sala      text unique,
    codigo_validade  timestamptz,
    -- vínculo do aluno com a sala
    professor_id     bigint references public.usuarios (id) on delete set null,
    turma            text,
    sala_entrada_em  timestamptz,
    criado_em        timestamptz not null default now()
);

-- Apenas um login de professor pode existir (a professora Beatriz).
-- Todo cadastro feito pelo site entra como ALUNO.
create unique index if not exists usuarios_um_professor
    on public.usuarios (perfil) where perfil = 'PROFESSOR';

create index if not exists usuarios_professor_id_idx
    on public.usuarios (professor_id);

-- -------------------------------------------------------------- progresso
create table if not exists public.progresso_trilha (
    aluno_id       bigint not null references public.usuarios (id) on delete cascade,
    etapa_id       integer not null,
    acertos        integer not null default 0,
    concluida_em   timestamptz not null default now(),
    atualizada_em  timestamptz not null default now(),
    primary key (aluno_id, etapa_id)
);

create table if not exists public.progresso_jogo (
    aluno_id          bigint not null references public.usuarios (id) on delete cascade,
    fase_id           integer not null,
    melhor_pontuacao  integer not null default 0,
    concluida_em      timestamptz not null default now(),
    atualizada_em     timestamptz not null default now(),
    primary key (aluno_id, fase_id)
);

-- ------------------------------------------------------ trilha da professora
-- Ids novos começam em 1000 para nunca colidir com as etapas padrão (1, 2, 3...).
create sequence if not exists public.trilha_atividades_id_seq start with 1000;

create table if not exists public.trilha_atividades (
    professor_id   bigint not null references public.usuarios (id) on delete cascade,
    id             integer not null,
    posicao        integer not null,
    period         text not null,
    title          text not null,
    description    text not null,
    color          text not null default 'blue',
    eyebrow        text not null default '',
    lesson_title   text not null default '',
    intro          text not null default '',
    sections       jsonb not null default '[]'::jsonb,   -- blocos de leitura (com imagens)
    quiz           jsonb not null default '[]'::jsonb,
    minigame       jsonb not null default '{"type": "nenhum"}'::jsonb,
    atualizada_em  timestamptz not null default now(),
    primary key (professor_id, id)
);

-- ----------------------------------------------------------------- arenas
create table if not exists public.arenas (
    id              bigint generated by default as identity primary key,
    professor_id    bigint not null references public.usuarios (id) on delete cascade,
    professor_nome  text not null default '',
    codigo          text not null unique,
    nome            text not null,
    tamanho         smallint not null check (tamanho in (6, 8, 10)),
    mapa            text not null check (char_length(mapa) = tamanho * tamanho),
    direcao         text not null check (direcao in ('N', 'E', 'S', 'W')),
    limite_blocos   smallint not null default 0,
    status          text not null default 'aguardando'
                    check (status in ('aguardando', 'em_jogo', 'finalizada')),
    criada_em       timestamptz not null default now(),
    iniciada_em     timestamptz,
    finalizada_em   timestamptz
);

create index if not exists arenas_professor_id_idx on public.arenas (professor_id);

create table if not exists public.arena_equipes (
    arena_id   bigint not null references public.arenas (id) on delete cascade,
    chave      text not null,
    nome       text not null,
    cor        text not null,
    emoji      text not null,                -- nome do ícone da equipe (ex.: rocket)
    criada_em  timestamptz not null default now(),
    primary key (arena_id, chave)
);

create table if not exists public.arena_jogadores (
    arena_id          bigint not null,
    aluno_id          bigint not null references public.usuarios (id) on delete cascade,
    nome              text not null,
    equipe            text not null,
    entrou_em         timestamptz not null default now(),
    visto_em          timestamptz,           -- último sinal de vida (mostra quem está online)
    tentativas        integer not null default 0,
    dicas             integer not null default 0,
    concluiu          boolean not null default false,
    concluiu_em       timestamptz,
    tempo             integer,               -- segundos até chegar na bandeira
    blocos            integer,
    estrelas          smallint,
    ajuda             jsonb,                 -- pedido de ajuda aberto (ou null)
    ajudas_recebidas  integer not null default 0,
    ultimo_erro       text,
    primary key (arena_id, aluno_id),
    foreign key (arena_id, equipe)
        references public.arena_equipes (arena_id, chave) on delete cascade
);

create index if not exists arena_jogadores_aluno_id_idx on public.arena_jogadores (aluno_id);

-- --------------------------------------------------------------- segurança
alter table public.usuarios          enable row level security;
alter table public.progresso_trilha  enable row level security;
alter table public.progresso_jogo    enable row level security;
alter table public.trilha_atividades enable row level security;
alter table public.arenas            enable row level security;
alter table public.arena_equipes     enable row level security;
alter table public.arena_jogadores   enable row level security;

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'anon') then
        revoke all on all tables in schema public from anon, authenticated;
        revoke all on all sequences in schema public from anon, authenticated;
    end if;
end $$;

-- ------------------------------------------------- imagens das trilhas
-- Bucket público: os alunos veem as imagens pelo link; só o servidor
-- (com a chave secreta) consegue enviar ou apagar arquivos.
do $$
begin
    if to_regclass('storage.buckets') is not null then
        insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
        values ('trilha-imagens', 'trilha-imagens', true, 4194304,
                array['image/png', 'image/jpeg', 'image/webp', 'image/gif'])
        on conflict (id) do update
            set public = excluded.public,
                file_size_limit = excluded.file_size_limit,
                allowed_mime_types = excluded.allowed_mime_types;
    end if;
end $$;
