"""Conteudo e regras estaticas do jogo de programacao em blocos."""


TAMANHO_MAPA = 6
COMANDOS_PERMITIDOS = ("avancar", "virar_esquerda", "virar_direita")
ORIENTACOES = ("N", "E", "S", "W")
DESLOCAMENTOS = {
    "N": (-1, 0),
    "E": (0, 1),
    "S": (1, 0),
    "W": (0, -1),
}


FASES_JOGO = [
    {
        "id": 1,
        "titulo": "Primeiros passos",
        "descricao": "Leve o robô em linha reta até a bandeira.",
        "spawn": {"linha": 5, "coluna": 0, "orientacao": "N"},
        "paredes": [
            {"linha": 3, "coluna": 2},
            {"linha": 4, "coluna": 2},
        ],
        "bandeira": {"linha": 2, "coluna": 0},
        "limite_blocos": 3,
        "dica": "Cada bloco 'avançar' move o robô uma casa na direção em que ele olha.",
    },
    {
        "id": 2,
        "titulo": "Hora de virar",
        "descricao": "Faça uma curva para alcançar a bandeira sem tocar nas paredes.",
        "spawn": {"linha": 5, "coluna": 0, "orientacao": "N"},
        "paredes": [
            {"linha": 4, "coluna": 1},
            {"linha": 4, "coluna": 2},
            {"linha": 4, "coluna": 3},
            {"linha": 2, "coluna": 1},
            {"linha": 2, "coluna": 2},
            {"linha": 2, "coluna": 3},
        ],
        "bandeira": {"linha": 3, "coluna": 3},
        "limite_blocos": 7,
        "dica": "Suba duas casas, vire à direita e avance até a bandeira.",
    },
    {
        "id": 3,
        "titulo": "Caminho em zigue-zague",
        "descricao": "Combine avanços e curvas para atravessar o corredor.",
        "spawn": {"linha": 5, "coluna": 0, "orientacao": "E"},
        "paredes": [
            {"linha": 5, "coluna": 3},
            {"linha": 4, "coluna": 0},
            {"linha": 4, "coluna": 1},
            {"linha": 4, "coluna": 3},
            {"linha": 4, "coluna": 4},
            {"linha": 4, "coluna": 5},
            {"linha": 3, "coluna": 5},
            {"linha": 2, "coluna": 0},
            {"linha": 2, "coluna": 1},
            {"linha": 2, "coluna": 2},
            {"linha": 2, "coluna": 3},
            {"linha": 2, "coluna": 5},
            {"linha": 1, "coluna": 3},
            {"linha": 1, "coluna": 5},
        ],
        "bandeira": {"linha": 0, "coluna": 5},
        "limite_blocos": 15,
        "dica": "Quando uma parede fechar a frente, procure a próxima abertura lateral.",
    },
    {
        "id": 4,
        "titulo": "Corredor secreto",
        "descricao": "Atravesse o labirinto usando o menor caminho disponível.",
        "spawn": {"linha": 0, "coluna": 0, "orientacao": "E"},
        "paredes": [
            {"linha": 0, "coluna": 3},
            {"linha": 1, "coluna": 0},
            {"linha": 1, "coluna": 1},
            {"linha": 1, "coluna": 3},
            {"linha": 1, "coluna": 4},
            {"linha": 1, "coluna": 5},
            {"linha": 2, "coluna": 0},
            {"linha": 2, "coluna": 1},
            {"linha": 2, "coluna": 5},
            {"linha": 3, "coluna": 0},
            {"linha": 3, "coluna": 2},
            {"linha": 3, "coluna": 3},
            {"linha": 3, "coluna": 5},
            {"linha": 4, "coluna": 0},
            {"linha": 4, "coluna": 1},
            {"linha": 4, "coluna": 2},
            {"linha": 4, "coluna": 3},
            {"linha": 4, "coluna": 5},
            {"linha": 5, "coluna": 0},
            {"linha": 5, "coluna": 1},
            {"linha": 5, "coluna": 2},
            {"linha": 5, "coluna": 3},
        ],
        "bandeira": {"linha": 5, "coluna": 5},
        "limite_blocos": 16,
        "dica": "O caminho alterna entre direita, baixo, direita e baixo novamente.",
    },
    {
        "id": 5,
        "titulo": "Missão final",
        "descricao": "Use tudo o que aprendeu para vencer o maior labirinto.",
        "spawn": {"linha": 5, "coluna": 5, "orientacao": "W"},
        "paredes": [
            {"linha": 0, "coluna": 5},
            {"linha": 1, "coluna": 0},
            {"linha": 1, "coluna": 1},
            {"linha": 1, "coluna": 2},
            {"linha": 1, "coluna": 3},
            {"linha": 1, "coluna": 5},
            {"linha": 2, "coluna": 5},
            {"linha": 3, "coluna": 1},
            {"linha": 3, "coluna": 2},
            {"linha": 3, "coluna": 3},
            {"linha": 3, "coluna": 4},
            {"linha": 3, "coluna": 5},
            {"linha": 4, "coluna": 4},
            {"linha": 4, "coluna": 5},
            {"linha": 5, "coluna": 0},
            {"linha": 5, "coluna": 1},
            {"linha": 5, "coluna": 2},
        ],
        "bandeira": {"linha": 0, "coluna": 0},
        "limite_blocos": 24,
        "dica": "Siga o corredor: esquerda, cima, esquerda, cima, direita, cima e esquerda.",
    },
]


FASES_POR_ID = {fase["id"]: fase for fase in FASES_JOGO}
